### ISSUE TITLE
Update Artifact Version on README

### ISSUE THREAD

**Issue by philnate** [hertzsprung/hamcrest-json#1]
Hi the artifact version in README states 0.1, but the latest version is 0.2. Especially the given example (in README) isn't working for version 0.1.

**Comment by jdhoek** [comment]
@hertzsprung Could you cherry-pick the commit @dvberkel did fixing this issue? I ran in to the same problem as @philnate before figuring out `0.2` was available which does have the `sameJSONAs(String)` from the example.

**Comment by dvberkel** [comment]
The open pull request #5 addresses exactly this issue. So there is no need to cherry pick.

**Comment by hertzsprung** [comment]
Fixed by #5 and #10
