### ISSUE TITLE
Tests fail to compile with Oracle java6, OpenJDK7

### ISSUE THREAD

**Issue by timp21337** [hertzsprung/hamcrest-json#3]
Both give error: 
[ERROR] /hamcrest-json/src/test/java/uk/co/datumedge/hamcrest/json/SameJSONAsTest.java:[55,54] and(org.hamcrest.Matcher<? super java.lang.Object>) in org.hamcrest.core.CombinableMatcher.CombinableBothMatcher<java.lang.Object> cannot be applied to (org.hamcrest.Matcher<java.lang.String>)

[ERROR] hamcrest-json/src/test/java/uk/co/datumedge/hamcrest/json/SameJSONAsTest.java:[86,88] and(org.hamcrest.Matcher<? super java.lang.Object>) in org.hamcrest.core.CombinableMatcher.CombinableBothMatcher<java.lang.Object> cannot be applied to (org.hamcrest.Matcher<java.lang.String>)

**Comment by hertzsprung** [comment]
Not sure why this happened but Java 8 is a minimum going forward.
